[adm-1035] add static config

diff --git a/deploy/helm/template/deployment.yaml b/deploy/helm/template/deployment.yaml
--- a/deploy/helm/template/deployment.yaml
+++ b/deploy/helm/template/deployment.yaml
@@ -1,196 +1,98 @@
 apiVersion: apps/v1
 kind: Deployment
 metadata:
-  name: {{ template "kibana.fullname" . }}
-  labels: {{ include "kibana.labels" . | nindent 4 }}
-  {{- if .Values.annotations }}
-  annotations:
-    {{- range $key, $value := .Values.annotations }}
-    {{ $key }}: {{ $value | quote }}
-    {{- end }}
-  {{- end }}
+  labels:
+    app: kibana
+    release: kibana
+  name: kibana-kibana
+  namespace: logging
 spec:
-  replicas: {{ .Values.replicas }}
-  strategy:
-{{ toYaml .Values.updateStrategy | indent 4 }}
+  progressDeadlineSeconds: 600
+  replicas: 1
+  revisionHistoryLimit: 10
   selector:
     matchLabels:
-      app: {{ .Chart.Name }}
-      release: {{ .Release.Name | quote }}
+      app: kibana
+      release: kibana
+  strategy:
+    type: Recreate
   template:
     metadata:
       labels:
-        app: {{ .Chart.Name }}
-        release: {{ .Release.Name | quote }}
-        {{- range $key, $value := .Values.labels }}
-        {{ $key }}: {{ $value | quote }}
-        {{- end }}
-      annotations:
-        {{- range $key, $value := .Values.podAnnotations }}
-        {{ $key }}: {{ $value | quote }}
-        {{- end }}
-        {{/* This forces a restart if the configmap has changed */}}
-        {{- if .Values.kibanaConfig }}
-        configchecksum: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum | trunc 63 }}
-        {{- end }}
+        app: kibana
+        release: kibana
     spec:
-      automountServiceAccountToken: {{ .Values.automountToken }}
-{{- if .Values.priorityClassName }}
-      priorityClassName: {{ .Values.priorityClassName }}
-{{- end }}
-      securityContext:
-{{ toYaml .Values.podSecurityContext | indent 8 }}
-      {{- if .Values.serviceAccount }}
-      serviceAccount: {{ .Values.serviceAccount }}
-      {{- end }}
-      {{- if .Values.hostAliases }}
-      hostAliases: {{ toYaml .Values.hostAliases | nindent 6 }}
-      {{- end }}
-      volumes:
-        - name: kibana-tokens
-          emptyDir: {}
-        - name: elasticsearch-certs
-          secret:
-            secretName: {{ .Values.elasticsearchCertificateSecret }}
-        {{- if .Values.kibanaConfig }}
-        - name: kibanaconfig
-          configMap:
-            name: {{ template "kibana.fullname" . }}-config
-        {{- end }}
-        {{- range .Values.secretMounts }}
-        - name: {{ .name }}
-          secret:
-            secretName: {{ .secretName }}
-        {{- end }}
-        {{- if .Values.extraVolumes }}
-{{ toYaml .Values.extraVolumes | indent 8 }}
-        {{- end }}
-    {{- with .Values.nodeSelector }}
-      nodeSelector:
-{{ toYaml . | indent 8 }}
-    {{- end }}
-    {{- with .Values.affinity }}
-      affinity:
-{{ toYaml . | indent 8 }}
-    {{- end }}
-    {{- with .Values.tolerations }}
-      tolerations:
-{{ toYaml . | indent 8 }}
-    {{- end }}
-    {{- if .Values.imagePullSecrets }}
-      imagePullSecrets:
-{{ toYaml .Values.imagePullSecrets | indent 8 }}
-    {{- end }}
-      initContainers:
-      {{- if .Values.extraInitContainers }}
-      # Currently some extra blocks accept strings
-      # to continue with backwards compatibility this is being kept
-      # whilst also allowing for yaml to be specified too.
-      {{- if eq "string" (printf "%T" .Values.extraInitContainers) }}
-{{ tpl .Values.extraInitContainers . | indent 6 }}
-      {{- else }}
-{{ toYaml .Values.extraInitContainers | indent 6 }}
-      {{- end }}
-      {{- end }}
       containers:
-      - name: kibana
-        securityContext:
-{{ toYaml .Values.securityContext | indent 10 }}
-        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
-        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
-        env:
-          {{- if .Values.elasticsearchURL }}
-          - name: ELASTICSEARCH_URL
-            value: "{{ .Values.elasticsearchURL }}"
-          {{- else if .Values.elasticsearchHosts }}
-          - name: ELASTICSEARCH_HOSTS
-            value: "{{ .Values.elasticsearchHosts }}"
-          {{- end }}
-          - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
-            value: "{{ template "kibana.home_dir" . }}/config/certs/{{ .Values.elasticsearchCertificateAuthoritiesFile }}"
-          - name: SERVER_HOST
-            value: "{{ .Values.serverHost }}"
-          - name: ELASTICSEARCH_SERVICEACCOUNTTOKEN
-            valueFrom:
-              secretKeyRef:
-                name: {{ template "kibana.fullname" . }}-es-token
-                key: token
-                optional: false
-{{- if .Values.extraEnvs }}
-{{ toYaml .Values.extraEnvs | indent 10 }}
-{{- end }}
-{{- if .Values.envFrom }}
-        envFrom:
-{{ toYaml .Values.envFrom | indent 10 }}
-{{- end }}
+      - env:
+        - name: SERVER_PUBLICBASEURL
+          value: https://logs-univ.sirius.online
+        - name: ELASTICSEARCH_HOSTS
+          value: http://elasticsearch-master:9200
+        - name: SERVER_HOST
+          value: 0.0.0.0
+        image: cr.yandex/crpcm9tg75s8gu2hqkp9/kibana:7.16.1
+        imagePullPolicy: IfNotPresent
+        name: kibana
+        ports:
+        - containerPort: 5601
+          protocol: TCP
         readinessProbe:
-{{ toYaml .Values.readinessProbe | indent 10 }}
           exec:
             command:
-              - bash
-              - -c
-              - |
-                #!/usr/bin/env bash -e
+            - sh
+            - -c
+            - |
+              #!/usr/bin/env bash -e
+              http () {
+                  local path="${1}"
+                  set -- -XGET -s --fail
 
-                # Disable nss cache to avoid filling dentry cache when calling curl
-                # This is required with Kibana Docker using nss < 3.52
-                export NSS_SDB_USE_CACHE=no
+                  if [ -n "${ELASTICSEARCH_USERNAME}" ] && [ -n "${ELASTICSEARCH_PASSWORD}" ]; then
+                    set -- "$@" -u "${ELASTICSEARCH_USERNAME}:${ELASTICSEARCH_PASSWORD}"
+                  fi
 
-                http () {
-                    local path="${1}"
-                    set -- -XGET -s --fail -L
+                  STATUS=$(curl --output /dev/null --write-out "%{http_code}" -k "$@" "http://localhost:5601${path}")
+                  if [[ "${STATUS}" -eq 200 ]]; then
+                    exit 0
+                  fi
 
-                    if [ -n "${ELASTICSEARCH_USERNAME}" ] && [ -n "${ELASTICSEARCH_PASSWORD}" ]; then
-                      set -- "$@" -u "${ELASTICSEARCH_USERNAME}:${ELASTICSEARCH_PASSWORD}"
-                    fi
+                  echo "Error: Got HTTP code ${STATUS} but expected a 200"
+                  exit 1
+              }
 
-                    STATUS=$(curl --output /dev/null --write-out "%{http_code}" -k "$@" "{{ .Values.protocol }}://localhost:{{ .Values.httpPort }}${path}")
-                    if [[ "${STATUS}" -eq 200 ]]; then
-                      exit 0
-                    fi
-
-                    echo "Error: Got HTTP code ${STATUS} but expected a 200"
-                    exit 1
-                }
-
-                http "{{ .Values.healthCheckPath }}"
-        ports:
-        - containerPort: {{ .Values.httpPort }}
-{{- if .Values.lifecycle }}
-        lifecycle:
-{{ toYaml .Values.lifecycle | indent 10 }}
-{{- end }}
+              http "/app/kibana"
+          failureThreshold: 3
+          initialDelaySeconds: 10
+          periodSeconds: 10
+          successThreshold: 3
+          timeoutSeconds: 5
         resources:
-{{ toYaml .Values.resources | indent 10 }}
-        volumeMounts:
-          - name: elasticsearch-certs
-            mountPath: {{ template "kibana.home_dir" . }}/config/certs
-            readOnly: true
-          - name: kibana-tokens
-            mountPath: {{ template "kibana.home_dir" . }}/config/tokens
-            readOnly: true
-          {{- range .Values.secretMounts }}
-          - name: {{ .name }}
-            mountPath: {{ .path }}
-            {{- if .subPath }}
-            subPath: {{ .subPath }}
-            {{- end }}
-          {{- end }}
-          {{- range $path, $config := .Values.kibanaConfig }}
-          - name: kibanaconfig
-            mountPath: {{ template "kibana.home_dir" . }}/config/{{ $path }}
-            subPath: {{ $path }}
-          {{- end -}}
-        {{- if .Values.extraVolumeMounts }}
-{{ toYaml .Values.extraVolumeMounts | indent 10 }}
-        {{- end }}
-      {{- if .Values.extraContainers }}
-      # Currently some extra blocks accept strings
-      # to continue with backwards compatibility this is being kept
-      # whilst also allowing for yaml to be specified too.
-      {{- if eq "string" (printf "%T" .Values.extraContainers) }}
-{{ tpl .Values.extraContainers . | indent 6 }}
-      {{- else }}
-{{ toYaml .Values.extraContainers | indent 6 }}
-      {{- end }}
-      {{- end }}
+          limits:
+            cpu: 800m
+            memory: 2Gi
+          requests:
+            cpu: 100m
+            memory: 300Mi
+        securityContext:
+          capabilities:
+            drop:
+            - ALL
+          runAsNonRoot: true
+          runAsUser: 1000
+        terminationMessagePath: /dev/termination-log
+        terminationMessagePolicy: File
+      dnsPolicy: ClusterFirst
+      imagePullSecrets:
+      - name: sirius-registry
+      nodeSelector:
+        node-role: monitoring
+      restartPolicy: Always
+      schedulerName: default-scheduler
+      securityContext:
+        fsGroup: 1000
+      terminationGracePeriodSeconds: 30
+      tolerations:
+      - effect: NoSchedule
+        key: node-role
+        operator: Equal
+        value: monitoring
